# 生成物，勿手改。由 tools/topics/sync-px4-msg.py 从 ConfigOverrides.msg 生成
topic: config_overrides
msg: ConfigOverrides.msg
fields:
  timestamp:
    type: uint64
    unit: us
  disable_auto_disarm:
    type: bool
    unit: if configured
    note: Prevent the drone from automatically disarming after landing (if configured)
  defer_failsafes:
    type: bool
    unit: until the flag is cleared
    note: Defer all failsafes that can be deferred (until the flag is cleared)
  defer_failsafes_timeout_s:
    type: int16
    note: Maximum time a failsafe can be deferred. 0 = system default, -1 = no timeout
  disable_auto_set_home:
    type: bool
    note: Prevent the drone from automatically setting the home position on arm or takeoff
  source_type:
    type: int8
    values:
      0: MODE
      1: EXECUTOR
    kind: enum
  source_id:
    type: uint8
    note: ID depending on source_type
