# 生成物，勿手改。由 tools/topics/sync-px4-msg.py 从 LongitudinalControlConfiguration.msg 生成
topic: longitudinal_control_configuration
msg: LongitudinalControlConfiguration.msg
fields:
  timestamp:
    type: uint64
    unit: us
  pitch_min:
    type: float32
    note: "[rad] [@range -pi, pi] Defaults to FW_P_LIM_MIN if NAN."
  pitch_max:
    type: float32
    note: "[rad] [@range -pi, pi] Defaults to FW_P_LIM_MAX if NAN."
  throttle_min:
    type: float32
    note: "[norm] [@range 0,1] Defaults to FW_THR_MIN if NAN."
  throttle_max:
    type: float32
    note: "[norm] [@range 0,1] Defaults to FW_THR_MAX if NAN."
  climb_rate_target:
    type: float32
    note: "[m/s] Target climbrate to change altitude. Defaults to FW_T_CLIMB_MAX if NAN. Not used if height_rate is directly set in FixedWingLongitudinalSetpoint."
  sink_rate_target:
    type: float32
    note: "[m/s] Target sinkrate to change altitude. Defaults to FW_T_SINK_MAX if NAN. Not used if height_rate is directly set in FixedWingLongitudinalSetpoint."
  speed_weight:
    type: float32
    note: "[-] [@range 0,2] 0=pitch controls altitude only, 2=pitch controls airspeed only"
  enforce_low_height_condition:
    type: bool
    note: If true, the altitude controller is configured with an alternative timeconstant for tighter altitude tracking
  disable_underspeed_protection:
    type: bool
    note: If true, underspeed handling is disabled in the altitude controller
